BUILD-1287 Add .github/CODEOWNERS
SonarSource/gh-action-lt-backlog pull request #1
Opened 2022-02-02 17:12 UTC by julien-carsique-sonarsource

Set the team @SonarSource/languages-team as code owner in `.github/CODEOWNERS` file.

This is required by [BUILD-1271](https://jira.sonarsource.com/browse/BUILD-1271).
Contact @SonarSource/re-team for more information.

2022-03-17 18:15 UTC, Godin requested changes
@julien-carsique-sonarsource this repository has only two branches - yours and `master` that contains `LICENSE` and `README.md` thus personally I don't see anything useful in it and don't know who asked its creation. @malena-ebert-sonarsource is the only committer, so maybe she remembers? I personally think that we should simply remove this repository since there was no commits in past 4 months.

2022-03-18 07:50 UTC, malena-ebert-sonarsource commented
> @malena-ebert-sonarsource is the only committer, so maybe she remembers?

It was requested by @pavel-mikula-sonarsource

2022-03-18 07:56 UTC, pavel-mikula-sonarsource commented
Yes, I confirm we'll need this. I just didn't have time to put content in the repository yet.

2022-03-18 07:58 UTC, pavel-mikula-sonarsource submitted a review, later dismissed

2022-03-18 07:58 UTC, pavel-mikula-sonarsource commented on .github/CODEOWNERS
> +* @sonarsource/languages-team
This should be
```suggestion
.github/CODEOWNERS @sonarsource/languages-team
```
or
```suggestion
.github/CODEOWNERS @SonarSource/languages-team-dotnet
```

We'll put some GitHub actions here that are intended to be shared with other bubbles using GitHub Kanbas and backlog. I expect .NET Bubble to be the main contributor.

2022-03-21 09:34 UTC, Godin approved these changes

2022-03-21 09:35 UTC, merged