Standalone PR sets additional Jira fields
SonarSource/gh-action-lt-backlog pull request #116
Opened 2024-07-31 16:51 UTC by sebastien-marichal

Fixes #102

2024-07-31 17:23 UTC, pavel-mikula-sonarsource requested changes
Let's simplify this

2024-07-31 17:23 UTC, pavel-mikula-sonarsource commented on PullRequestCreated/ReadMe.md
> +additional-fields: '{ "fixVersions": [ { "id": "15601" } ] }'
FixVersion is a short live value that changes often, therefore it's not very suitable for the demo here.  Can you use something else, like label, component, or priority? Something that can be done in a simple way.

2024-07-31 17:23 UTC, pavel-mikula-sonarsource commented on PullRequestCreated/PullRequestCreated.ts
> +    let addutinalFields = {};
metabuerguer 😆 
```suggestion
    let additionalFields = {};
```

2024-07-31 17:23 UTC, pavel-mikula-sonarsource commented on PullRequestCreated/PullRequestCreated.ts
> +        addutinalFields = { ...addutinalFields, ...fields };
This should not be inside the `try`. What about extracting `parseAdditionalFields` that would return the object, or null? And here, we would use the resulting value
```suggestion
```

2024-07-31 17:23 UTC, pavel-mikula-sonarsource commented on PullRequestCreated/PullRequestCreated.ts
> +    }
This looks weird. What about removing `issueType: string` from `createIssue`, make `additionalFields` mandatory and pass issueType via that?
Then here, there would be something like 
```
  return { ...this.parseAdditionalFields(), ...parameters}
```

2024-07-31 17:23 UTC, pavel-mikula-sonarsource commented on PullRequestCreated/PullRequestCreated.ts
> +        addutinalFields = { ...addutinalFields, ...fields };
..or empty object `{ }` instead of null, after updatin the other comment about `...` usage

2024-07-31 17:25 UTC, sebastien-marichal commented on PullRequestCreated/PullRequestCreated.ts
> +    let addutinalFields = {};
The heat is not helping me today... 🤦

2024-07-31 17:29 UTC, pavel-mikula-sonarsource commented on PullRequestCreated/ReadMe.md
Please update the intro to document the functionality that this action does. Like updating issue title and issue description

2024-08-06 12:51 UTC, pavel-mikula-sonarsource approved these changes
LGTM, with some final polishing

2024-08-06 12:51 UTC, pavel-mikula-sonarsource commented on PullRequestCreated/ReadMe.md
> +The action will link all mentioned tickets in the title into the description.
```suggestion
The action will update the PR description with links to all mentioned Jira tickets for easy navigation.
```

2024-08-06 12:51 UTC, pavel-mikula-sonarsource commented on PullRequestCreated/ReadMe.md
> +This action will also update the PR title and description to mention the right Jira tickets.
I don't understand what this means. It looks like a combination of the next two points.
```suggestion
```

2024-08-06 12:51 UTC, pavel-mikula-sonarsource commented on PullRequestCreated/ReadMe.md
> +When creating a ticket, the action will add it to the PR title.
This should be before the point about updating the description, to keep them in (chrono)logical order
```suggestion
When creating a new Jira issue, the action will add the new issue ID to the PR title.
```

2024-08-06 12:51 UTC, pavel-mikula-sonarsource commented on PullRequestCreated/PullRequestCreated.ts
> +    return { ...this.parseAdditionalFields(), ...parameters }
Can we embed the `{...}` into the call site? It looks like unneeded indirection now

2024-08-06 13:02 UTC, merged