Use Repox as npm registry
SonarSource/gh-action-lt-backlog pull request #99
Opened 2024-07-25 07:10 UTC by sebastien-marichal

2024-07-25 12:34 UTC, pavel-mikula-sonarsource requested changes
This was painful copy paste issue :(

2024-07-25 14:18 UTC, sebastien-marichal commented on README.md
> +//repox.jfrog.io/artifactory/api/npm/npm/:_auth = <npm-repox-token>
I am using this locally...

2024-07-25 14:27 UTC, sebastien-marichal commented on README.md
> +//repox.jfrog.io/artifactory/api/npm/npm/:_auth = <npm-repox-token>
`_auth` is for tokens that are base64 encoded while `_authToken` is not.

2024-07-26 06:14 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2024-07-26 06:14 UTC, merged